name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Lint the code
      run: swiftlint lint

  build-macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Test on Mac
      run: swift test
